name: Update dependencies
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  update_deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: rm -rf package-lock.json
    - run: npx npm-check-updates -u -x serialport # serialport is currently broken: https://github.com/Koenkk/zigbee-herdsman/issues/540
    - run: npm install
    - uses: peter-evans/create-pull-request@v4
      with:
        commit-message: Update dependencies
        branch: "update_deps"
        title: Update dependencies
